-- DECLARE
--  <VARIABLE NAME> <DATA TYPE>:=<INITIAL VALUE>;
-- BEGIN 
--   DBMS_OUTPUT.PUT_LINE('MESSAGE '+<VARIABLE NAME>);
-- END;
-- /

--------BELOW IS ANONYMOUS BLOCK
DECLARE
  A NUMBER;
  B NUMBER;
  C NUMBER;
FUNCTION FINMAX(X IN NUMBER, Y IN NUMBER) 
RETURN NUMBER
  IS Z NUMBER;
BEGIN 
  IF X>Y THEN
    Z:=X;
  ELSE
    Z:=Y;
  END IF;
RETURN Z;
END;

BEGIN 
  A:=23;
  B:=45;
  C:=FINDMAX(A,B);
  DBMS_OUTPUT.PUTLINE('MAXIMUM OF (23,45): ' || C);
END;
/
